# Generated by Django 6.0.3 on 2026-03-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SklepApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='produkcts',
            new_name='products',
        ),
    ]
