# Generated by Django 6.0.3 on 2026-03-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SklepApp', '0002_rename_produkcts_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
